[common]
title = "Weibel Instability."
dir = "data"

[physical.species]
name =   ["electron", "ion"]
mass =   [ 1,        1836]
charge = [ -1,       1]

# electron
[[physical.species.V_distribution]]
type = "normal"
params = [0.0316, 0.0316, 0.1]
[[physical.species.R_distribution]]
type = "uniform"

# ion
[[physical.species.V_distribution]]
type = "normal"
params = [0.0316, 0.0316, 0.1]
[[physical.species.R_distribution]]
type = "uniform"

[physical.domain_size]
space = 5.24
time = 50

[numerical]
cells_num = 256
time_step = 0.25
particles_per_cell = [1000, 1000]
prestart_steps = 50

[out]
particle_dens_span = [10, 50]
